### ISSUE TITLE
Please extern descrs[] from mgos_deps_init.c

### ISSUE THREAD

**Issue by Harvie** [mongoose-os/mos#34]
Hello,
i would like to get list of names of active mongoose modules during runtime. Can you please make data from descrs[] array accesible using some header file which can be included in my modules?

I want to use this to send JSON list of modules to my cloud/server, so i know what modules/capabilities each device provides and therefore i know which features i can use... Because i have several devices which share some of the modules, while other modules are specific. It makes more sense to me than using several "versions" of API for each device configuration. This way i would simply know what modules are present in the device, so i can write nice modular API on the server.

BTW if you add version of each module to the list, it might be usefull as well.

Thanks

**Comment by rojer** [comment]
makes sense. nothing to do with this repo though, this one is for mos the CLI tool.
please file under cesanta/mongoose-os.

**Comment by Harvie** [comment]
Sorry. I am still bit confused about various repos and github accounts that mongoose uses :-D

Moved here: https://github.com/cesanta/mongoose-os/issues/536
