### ISSUE TITLE
mdash-setup and gcp-iot-setup shouldn't write to conf9.json

### ISSUE THREAD

**Issue by nated0g** [mongoose-os/mos#36]
Not a bug per se, but I'd like to request that `mos mdash-setup` and `mos gcp-iot-setup` write credentials to a lower config level than conf9.json.

We have had an issue where on a production device, if a write to config gets interrupted during normal operation, like by say a power issue, and conf9.json gets corrupted as a result, the device can no longer connect to the cloud.  It makes sense for wifi credentials to be stored here, but in a commercial, production device, cloud credentials are vendor level configuration and don't belong here.

Currently our solution will be to run these commands at device commissioning time, get them from the device config with RPC over UART, put in conf5.json, and write back to the device.  This adds time unnecessarily to our setup process.  Maybe I am missing the intended use-case, but I really can't see many situations where storing this stuff in conf9.json is an advantage.

**Comment by rojer** [comment]
you can specify `--level=N` to set the config level.

**Comment by nated0g** [comment]
Cool, that's what I needed.  I couldn't find that in the docs anywhere.
