### ISSUE TITLE
Error in documentation for installation on Arch Linux

### ISSUE THREAD

**Issue by PRO2XY** [mongoose-os/mos#5]
On the readme, there is [this](https://github.com/mongoose-os/mos#installing-on-arch-linux)

> `git clone https://github.com/cesanta/mos-tool`

which references the old repository which is empty. 

Edit: Looks like same error for Mac OS as well. And same in the [**docs** ](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md)

**Comment by solarkraft** [comment]
Maybe it's a good idea to re-open this issue, as it is still present on the [documentation page](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md).
