### ISSUE TITLE
mos 2.19.1 clone not working

### ISSUE THREAD

**Issue by Sekilsgs2** [mongoose-os/mos#55]
In 2.19.1 when i'm run mos clone - i'm get error - 

```
$ mos clone https://github.com/mongoose-os-apps/demo-js app_test
Error: app_test: Local copy in "demo-js" does not exist and fetching is not allowed
/src/cli/build/swmodule.go:262: 
/src/cli/main.go:198: clone failed
exit status 1
Command completed.
```

**Comment by retecata** [comment]
Hi! I just wanted to jump in and say I am getting the same error!

**Comment by rojer** [comment]
fixed now, apologies!

**Comment by rojer** [comment]
fixed build pushed to latest

**Comment by retecata** [comment]
Hi! thank you for the quick replies. Does this apply to the pre-built mos.exe for Windows as well? I'm trying to run this on Windows and I'm getting the same error.

**Comment by felixback84** [comment]
hi guys I am getting the same error.... how i can solve it????

```
$ mos clone https://github.com/mongoose-os-apps/demo-js app1
Error: app1: Local copy in "demo-js" does not exist and fetching is not allowed
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/build/swmodule.go:262: 
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/main.go:198: clone failed
exit status 1
Command completed.
```

thanks fon any help...

**Comment by felixback84** [comment]
> fixed build pushed to latest

What do you mean whit this??? Thanks for the help...

**Comment by rakeshyannamani** [comment]
![image](https://user-images.githubusercontent.com/6128116/123147826-20ba1a80-d47d-11eb-8bf9-f0197a7c5287.png)

How can i solve this ?

**Comment by rojer** [comment]
swithc to latest (mos update latest) or wait for the next release (2.20).

**Comment by JanS1977** [comment]
### Workaround

This was tested in a terminal.

First, create a folder. Name it like the app you want to clone. In this case it would be:
`mkdir demo-js`
Then go with your standard mos clone command. In this case:
`mos clone demo-js app1`
Spelling out the whole Github path also works fine.

Mos will do the cloning and rename the folder you created to app1.

Hope this helps. Happy coding. :)
