### ISSUE TITLE
Mos tool cloning not working

### ISSUE THREAD

**Issue by Rossigg** [mongoose-os/mos#61]
I'm on mos tool 2.19.1 on Windows and when I'm trying to run the command
`mos clone https://github.com/mongoose-os-apps/demo-js app1`
I always getting this error
`Error: app1: Local copy in "demo-js" does not exist and fetching is not allowed
/src/cli/build/swmodule.go:262: 
/src/cli/main.go:198: clone failed
exit status 1`
I already saw that this issue was asked in the past, but the bug persist.
I do not know what to do
![Untitled](https://user-images.githubusercontent.com/56557442/114426595-83a84f00-9bba-11eb-95c6-6464c7fed4d4.png)

**Comment by mggil7** [comment]
Were you able to solve this issue? If so, can you please let me know? I am facing the same issue. I appreciate your help. Thank you
